# Generated by Django 4.2.7 on 2023-12-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_vendor_contact_details_alter_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
